version: 2
jobs:
  build:
    working_directory: ~/CircleCi
    docker:
      - image: circleci/node: 7
    steps:
      - checkout
      - run:
          npm install
      - run:
          npm test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

