version: 2
jobs:
  build:
    docker:
        - image: circleci/node: 7
    working_directory: ~/CircleCi
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

